# Generated by Django 4.2.25 on 2026-02-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_complaint_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table_sub',
            name='Total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
